### PR TITLE
3.0.0 and 2.11.4.0 Exoplayer extension

### LINKED ISSUE #32: Unable to resolve getDefaultScrubberColor method in PreviewTimeBar
The PreviewTimeBar class makes a call to getDefaultScrubberColor but it seems like that method no longer exists in recent versions of ExoPlayer.

### PR DESCRIPTION
**Pull request by rubensousa**
Fixes #32 and #35

### CODE REVIEW

**Comment by yoobi** [comment]
Do you need help in updating the library?

**Comment by rubensousa** [comment]
Yes, I would appreciate if you can check the develop branch if there's something extra you need for the next release.

**Comment by yoobi** [comment]
I've tested it with 2 phones (API 19 and 26) it worked well, I don't see anything else to add

**Comment by rubensousa** [comment]
Thanks @yoobi. I'll try to release this by the end of the week

**Comment by rubensousa** [comment]
@yoobi release is done :)

**Pull request merged**
