### PR TITLE
Update dependencies and migrate to AndroidX

### PR DESCRIPTION
**Pull request by rubengees**
This PR migrates the project to AndroidX and updates all dependencies to the latest stable versions.

`ExoPlayer` introduced breaking changes with it's latest version and the code was updated to match the new APIs. This library cannot be used without these adjustments anymore and crashes immediately.

I also did some other minor improvements whenever I saw something throughout the code.

### CODE REVIEW

**Comment by rubensousa** [comment]
Can you open this against develop branch instead of master?

**Comment by rubengees** [comment]
Sure, I have changed the base.

**Comment by rubensousa** [comment]
Thank you for the help. I'll try to release an update once I have more time

**Comment by rubengees** [comment]
Cool, thanks. Looking forward!

**Pull request merged**
